proxy-app = "tcp://127.0.0.1:26658"
moniker = "node-1"
mode = "full"
db-backend = "goleveldb"
db-dir = "data"
log-level = "info"
log-format = "plain"
genesis-file = "config/genesis.json"
node-key-file = "config/node_key.json"
abci = "socket"
filter-peers = false

[priv-validator]
key-file = "config/priv_validator_key.json"
state-file = "data/priv_validator_state.json"
laddr = ""
client-certificate-file = ""
client-key-file = ""
root-ca-file = ""

[rpc]
laddr = "tcp://127.0.0.1:26657"
cors-allowed-origins = []
cors-allowed-methods = [ "HEAD", "GET", "POST" ]
cors-allowed-headers = [ "Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time" ]
unsafe = false
max-open-connections = 900
max-subscription-clients = 100
max-subscriptions-per-client = 5
experimental-disable-websocket = false
event-log-window-size = "30s"
event-log-max-items = 0
timeout-broadcast-tx-commit = "10s"
max-body-bytes = 1000000
max-header-bytes = 1048576
tls-cert-file = ""
tls-key-file = ""
pprof-laddr = "localhost:6060"

[p2p]
queue-type = "simple-priority"
laddr = "tcp://0.0.0.0:26656"
external-address = ""
bootstrap-peers = ""
persistent-peers = "c32e1c3686467d56010c1d19dfaab8fa041bdd69@15.184.129.153:26656,e662d63ef5b21b37fc54bb0d0b69470696ccaf57@13.126.68.55:26656,90dba23338cc4ad4d41311a45bab7d712d8ce626@13.202.156.126:26656"
upnp = false
max-connections = 200
max-incoming-connection-attempts = 100
pex = true
private-peer-ids = ""
allow-duplicate-ip = false
handshake-timeout = "20s"
dial-timeout = "3s"
flush-throttle-timeout = "10ms"
max-packet-msg-payload-size = 1000000
send-rate = 20480000
recv-rate = 20480000
unconditional-peer-ids = ""

[mempool]
broadcast = true
size = 1000
max-txs-bytes = 10737418240
cache-size = 10000
keep-invalid-txs-in-cache = false
max-tx-bytes = 2048576
max-batch-bytes = 0
ttl-duration = "30s"
ttl-num-blocks = 100
tx-notify-threshold = 0
check-tx-error-blacklist-enabled = false
check-tx-error-threshold = 0
pending-size = 5000
max-pending-txs-bytes = 1073741824
pending-ttl-duration = "0s"
pending-ttl-num-blocks = 0

[statesync]
enable = false
use-p2p = false
rpc-servers = ""
trust-height = 0
trust-hash = ""
trust-period = "168h0m0s"
backfill-blocks = "0"
backfill-duration = "0s"
discovery-time = "15s"
temp-dir = ""
chunk-request-timeout = "15s"
fetchers = "4"
verify-light-block-timeout = "1m0s"
blacklist-ttl = "5m0s"

[consensus]
wal-file = "data/cs.wal/wal"
double-sign-check-height = 0
create-empty-blocks = true
create-empty-blocks-interval = "0s"
gossip-tx-key-only = "true"
peer-gossip-sleep-duration = "100ms"
peer-query-maj23-sleep-duration = "2s"
unsafe-propose-timeout-override = "300ms"
unsafe-propose-timeout-delta-override = "50ms"
unsafe-vote-timeout-override = "50ms"
unsafe-vote-timeout-delta-override = "50ms"
unsafe-commit-timeout-override = "200ms"

[tx-index]
indexer = [ "kv" ]
psql-conn = ""

[instrumentation]
prometheus = true
prometheus-listen-addr = ":26660"
max-open-connections = 3
namespace = "tendermint"

[self-remediation]
p2p-no-peers-available-window-seconds = 0
statesync-no-peers-available-window-seconds = 0
blocks-behind-threshold = 0
blocks-behind-check-interval = 60
restart-cooldown-seconds = 600

[db-sync]
db-sync-enable = "false"
snapshot-interval = "0"
snapshot-directory = ""
snapshot-worker-count = "16"
timeout-in-seconds = "1200"
no-file-sleep-in-seconds = "1"
file-worker-count = "32"
file-worker-timeout = "30"
trust-height = "0"
trust-hash = ""
trust-period = "24h0m0s"
verify-light-block-timeout = "1m0s"
blacklist-ttl = "5m0s"